import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const optionalString = v.optional(v.string());
const optionalNumber = v.optional(v.number());
const optionalBoolean = v.optional(v.boolean());
const optionalNullableNumber = v.optional(v.union(v.number(), v.null()));

export default defineSchema({
  clients: defineTable({
    externalId: v.string(),
    number: optionalNumber,
    name: v.string(),
    team: optionalString,
    responsible: optionalString,
    shareRaw: optionalString,
    sharePct: optionalNullableNumber,
    vatRaw: optionalString,
    vatRegistered: optionalBoolean,
    contractRaw: optionalString,
    contractStatus: optionalString,
    operationalStatus: optionalString,
    whatsappGroup: optionalString,
    sellerLevel: optionalString,
    sellerType: optionalString,
    contractNotes: optionalString,
    ebayUsername: optionalString,
    ebayPassword: optionalString,
    ipProtocol: optionalString,
    ipHost: optionalString,
    ipPort: optionalString,
    ipUsername: optionalString,
    ipPassword: optionalString,
    ipAddress: optionalString,
    aliexpressEmail: optionalString,
    aliexpressPassword: optionalString,
    picodiEmail: optionalString,
    picodiPassword: optionalString,
    plSheet: optionalString,
    plSheetLabel: optionalString,
    notes: optionalString,
    sourceRow: optionalNumber,
    auditFlags: v.optional(v.array(v.string())),
    assistant: optionalString,
    workMode: optionalString,
    partnerName: optionalString,
    partnerPct: optionalNumber,
    officeChargeDefault: optionalNumber,
    officeChargeMethod: optionalString,
    careLevel: optionalString,
    careUntil: optionalString,
    careNotes: optionalString,
  })
    .index("by_external_id", ["externalId"])
    .index("by_team", ["team"]),
  leads: defineTable({
    externalId: v.string(),
    number: optionalNumber,
    name: v.string(),
    dateAdded: optionalString,
    phoneOrWhatsapp: optionalString,
    platforms: optionalString,
    accountType: optionalString,
    country: optionalString,
    source: optionalString,
    referredBy: optionalString,
    agreedStatus: optionalString,
    agreedPct: optionalNullableNumber,
    spoken: optionalString,
    stage: optionalString,
    notes: optionalString,
    sourceRow: optionalNumber,
  })
    .index("by_external_id", ["externalId"])
    .index("by_stage", ["stage"]),
  plEntries: defineTable({
    externalId: v.string(),
    clientExternalId: v.string(),
    clientName: optionalString,
    team: optionalString,
    assistantName: optionalString,
    partnerName: optionalString,
    month: v.string(),
    gross: optionalNumber,
    expenses: optionalNumber,
    net: optionalNumber,
    baseProfit: optionalNumber,
    serviceCharges: optionalNumber,
    serviceChargesCollected: optionalNumber,
    officeCharge: optionalNumber,
    officeChargeMethod: optionalString,
    gbpReceived: optionalNumber,
    pkrReceived: optionalNumber,
    gbpPkrRate: optionalNumber,
    invoiceSent: optionalString,
    collectionStatus: optionalString,
    tlPaid: optionalString,
    vaPaid: optionalString,
    partnerPaid: optionalString,
    yasirPaid: optionalString,
    zubairPaid: optionalString,
    splitBase: optionalNumber,
    agencyBeforeCharge: optionalNumber,
    agencyShare: optionalNumber,
    amountOwedGbp: optionalNumber,
    clientShare: optionalNumber,
    vaPct: optionalNumber,
    tlPct: optionalNumber,
    vaShare: optionalNumber,
    tlShare: optionalNumber,
    partnerShare: optionalNumber,
    yasirShare: optionalNumber,
    zubairShare: optionalNumber,
    notes: optionalString,
  })
    .index("by_external_id", ["externalId"])
    .index("by_client", ["clientExternalId"])
    .index("by_month", ["month"]),
  cables: defineTable({
    externalId: v.string(),
    clientExternalId: v.string(),
    clientName: optionalString,
    date: optionalString,
    amount: optionalNumber,
    paid: optionalString,
    notes: optionalString,
  }).index("by_external_id", ["externalId"]),
  settings: defineTable({
    key: v.string(),
    values: v.array(v.string()),
  }).index("by_key", ["key"]),
  metadata: defineTable({
    key: v.string(),
    value: v.any(),
  }).index("by_key", ["key"]),
});
